#define FIRMWARE_VERSION F(__DATE__ " " __TIME__)

#define DEFAULT_HOSTNAME F("ufo")
#define DEFAULT_APSSID F("ufo")

// ESP8266 Huzzah Pin usage
#define PIN_DOTSTAR_LOGO 5
#define PIN_DOTSTAR_LOWERRING 0
#define PIN_DOTSTAR_UPPERRING 4
#define PIN_DOTSTAR_CLOCK 16
#define PIN_FACTORYRESET 15

